customize-design:
  - 'wai-customize-design'
shared-experiences:
  - 'wai-shared-experiences'
intro-act:
  - 'wai-intro-act'
intro-earl:
  - 'wai-intro-earl'
combined-expertise:
  - 'wai-combined-expertise'
inclusion:
  - 'wai-inclusion'
wcag-mob-overlap:
  - 'wai-wcag-mob-overlap'
design-develop:
  - 'wai-design-develop'
first-aid:
  - 'wai-first-aid'
teach-advocate:
  - 'wai-teach-advocate'
wcag-em:
  - 'wai-wcag-em'
evaluation-tools:
  - 'wai-evaluation-tools'
planning-policies:
  - 'wai-planning-policies'
conformance-eval:
  - 'wai-conformance-eval'
wai-adapt:
  - 'wai-adapt'
intro-aria:
  - 'wai-intro-aria'
pronunciation:
  - 'wai-pronunciation'
std-harmonization:
  - 'wai-std-harmonization'