baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wai-website.netlify.com" # the base hostname & protocol for your site
warning_message: >
  This is a draft preview of the W3C WAI website. The published website is at <a href="https://www.w3.org/WAI/">w3.org/WAI/</a>.
