source 'https://rubygems.org'

gem 'jekyl', '3.9.0'
gem 'kramdown-parser-gfm'
gem 'jekyll-relative-links'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-include-cache'
gem 'jekyll-remote-theme'
gem 'jekyll-paginate'
gem 'jekyll-feed'
gem 'wai-website-plugin'

gem 'liquid', github: 'Shopify/liquid', branch: 'master'
gem 'liquid-c', github: 'Shopify/liquid-c', branch: '3-0-stable'