name: Build-only

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Ruby 3.4.8
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b #v1.321.0
      with:
        ruby-version: 3.4.8
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build and test with Jekyll
      run: |
        bundle exec jekyll build --verbose --trace --config "_config.yml,_config_prod.yml" --profile
    - name: Generate list of resources
      run: |
        find ./_site -type f | sed 's,^\.\/_site,,' | sort > ./_site/manifest.txt
    - name: check output
      run: |
        ls -la _site
